name: Flutter CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: flutter-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.41.0"
  FLUTTER_CHANNEL: "stable"
jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

  build_android:
    name: Build Android (APK/AAB)
    needs: analyze_and_test
    if: github.event_name == 'push' # chỉ build khi push/merge vào main
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up java 17
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '17'

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: ${{ env.FLUTTER_CHANNEL }}
            cache: true

        - name: pub get
          run: flutter pub get

        - name: Build APK
          run: flutter build apk --release

        - name: Build AAB
          run: flutter build appbundle --release

        - name: Upload Android artifacts
          uses: actions/upload-artifact@v4
          with:
            name: android-${{ github.sha }}
            if-no-files-found: error
            path: |
                build/app/outputs/flutter-apk/*.apk
                build/app/outputs/bundle/release/*.aab
